spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PerfisSantander
    username: postgres
    password: root
  jpa:
    database: H2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  main:
    allow-circular-references: true

    
    